/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: ElliotGriffiths (https://sketchfab.com/ElliotGriffiths24)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/gart230-diagnostics-screen-fe814ea2f9bf40998d63fc72a57452a2
title: GART230 - Diagnostics Screen
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Screen({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/model-transformed.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh castShadow receiveShadow geometry={nodes.defaultMaterial.geometry} material={materials.lambert1} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/model-transformed.glb')
